title: Resume - Vsevolod Mineev
description: Resume of Sebastian Mineev, Product Officer at QOVES. Personal profile, experience, education and skills.
url: https://www.sebastian-mineev.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier
    - jekyll-seo-tag

exclude:
  - docker-compose.yml
